### ISSUE TITLE
Edit the main page for good responsiveness

### ISSUE THREAD

**Issue by vikranth1997** [ShaastraWebops/CA-Site-2018#15]
@Ronitron007 Just a small one , shift the bar in which the youtube,fb,twitter links are shown from the bottom side to the right side.... decrease the thickness of this new side bar which u put on the right side vertically in a way that it shouldnt contrast the existing nav bar and put all the icons in the middle properly. 

Once its done push it nd close the issue

**Comment by gokulan97** [comment]
@vikranth1997 tell how will it look in the mobile. That's the reason this
issue want opened at all. This is not needed. Instead, @rohit, make the
main route adaptable to small screens too

On Jul 22, 2017 5:27 PM, "vikranth1997" <notifications@github.com> wrote:

@Ronitron007 <https://github.com/ronitron007> Just a small one , shift the
bar in which the youtube,fb,twitter links are shown from the bottom side to
the right side.... decrease the thickness of this new side bar which u put
on the right side vertically in a way that it shouldnt contrast the
existing nav bar and put all the icons in the middle properly.

Once its done push it nd close the issue

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ShaastraWebops/CA-Site-2018/issues/15>, or mute the
thread

**Comment by vikranth1997** [comment]
@gokulan97 thats why bootstrap is there to adjust it to the mobile version... ok @Ronitron007 leave the work that i've given u cauz gokulan isnt accepting about this...we'll let u know soon...

For now u adjust the responsiveness of the mobile site.....try to adjust the AMBASSADOR word properly in the mobile version nd also the remaining parts (**What** part) also are not being show n in an orderly fashion...the responsiveness is not handled properly there...fix that nd push it. 

Acknowledge the issue !! and close once its done

**Comment by gokulan97** [comment]
Closing as completed.
